### ISSUE TITLE
Create TypeScript interface for data import

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#13]
- [x] Define and document TypeScript interface for the data
- [ ] Create mappings from shortcodes to full strings (e.g. Owner/Country, Launch Site)

**Comment by Bone008** [comment]
This is done, with a few nitpicks that still need to cleaned up at the source, see #12 

I have created a separate issue (#31) for the shortcode mapping since it is kind of unrelated.
