### ISSUE TITLE
Create UI design and mockups

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#14]
The goal here is to create a UI hierarchy/subdivision that allows us to separate work. We need heavy detail on the available transitions between views. Within a view we should develop a list of required UI features, but exactly where or how those are accomplished could remain undecided.

**Comment by avelinpv** [comment]
Rough sketches produced in the design directory. Details and hierchy comming on the next design meeting.

**Comment by avelinpv** [comment]
Navigation through the views added, as well as listed UI feature and listed views we need in the design. Some parts that are still not set need to be discussed in the whole group. More information on the dataset is needed to set more details on for eg. the things in the filter box.

**Comment by avelinpv** [comment]
![design_views_ideas](https://user-images.githubusercontent.com/30972483/154508982-0633d481-e11d-4aa0-9245-70bb5aaf8468.jpg)
![img1-1](https://user-images.githubusercontent.com/30972483/154508988-b53413ef-d0b4-4f13-9d2f-05b42715eed3.jpg)
![img2-1](https://user-images.githubusercontent.com/30972483/154508997-116ec9d7-b28c-4edc-a9e0-ee161d1519ee.jpg)
![img3-1](https://user-images.githubusercontent.com/30972483/154509005-f12d5d63-5b8c-4f9c-8472-f201ad566c6a.jpg)
![img4-1](https://user-images.githubusercontent.com/30972483/154509014-14ab6884-6d70-4625-af17-cdd6db1a9471.jpg)

**Comment by avelinpv** [comment]
[Feedback from HWD](https://docs.google.com/document/d/1NuxpmROd8XtMXJuiNdVedQVUIr-N_LrzRxzc3H8tM_A/edit?usp=sharing )

**Comment by Bone008** [comment]
Closing for now, remaining details that still need to be discussed will be put into separate small issues.
