### ISSUE TITLE
Implement 2D map view

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#17]
- [x] Render a 2D map
- [x] Enable SVG rendering on top
- [x] Add panning & zooming controls
- [x] Create interface for plotting...
     - [x] by country
     - [x] by coordinate (XY or lat-long... may overlap with math section)

**Comment by Bone008** [comment]
Possible library to use for rendering the world map: https://yanivam.github.io/react-svg-worldmap/

Should investigate if it easily allows drawing custom SVG elements based on lat/lng coordinates though, might be hard to "patch into" it.

**Comment by Bone008** [comment]
Done, further progress on this will be in #23 and #24
