### ISSUE TITLE
Implement rest of the logic for filter panel

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#18]
- [x] Create filter panel within UI
- [x] Add controls which affect global app state and the resulting visualizations

**Comment by Bone008** [comment]
In ae4d9e0145a74dfb4a51efda4a1d5876338dc546, I have created the `FilterPanel` component and added an example of generating a HTML <select> for filtering by orbit class that updates the global filter when the selection changes. Please use that as foundation for the rest of the filter controls.

**Comment by avelinpv** [comment]
Solve classes and types in a hierchy in the filter panel. somehow

**Comment by avelinpv** [comment]
Add to the filter panel:
- [x] Orbit class
- [x] Purpose
- [x] Owner (country)
- [x] Usage 
- [ ] Time period (is set by the timeline)
- [x] Active/Total

**Comment by sahilshahpatel** [comment]
@Bone008 When you re-added the filter count options there is still a problem. For example, if I select Elliptical -> US then the option to filter for Military will show up as "Military (10)." Let's say I click that and then *remove* the Elliptical filter. The tag for Military will still show "Military (10)" but at this point it should be "Military (122)" because the Elliptical filter was removed.

If it's possible not to show the number in the tag portion (the thing with the X) and only in the dropdown I think that would solve the problem, but I haven't thought it through fully.

**Comment by Bone008** [comment]
The rest of this issue is about hooking up logic to the new controls that will be added in #48

**Comment by Bone008** [comment]
I added logic for the "purpose" and "only active" filter options and fixed the count-update bug by hiding the count in the values that are shown in the collapsed dropdown.

To make the purpose dropdown less messy it still needs to cleaned up in the data source, see #12.
