### ISSUE TITLE
Set up D3.js and integrate it with React hooks

### ISSUE THREAD

**Issue by Bone008** [Bone008/orbiteye#29]
Probably a good up-to-date guide to follow (`useEffect` seems more modern than `componentDidMount`):

https://www.pluralsight.com/guides/using-d3.js-inside-a-react-app

The package "react-d3-library" seems outdated, badly documented and does not have TypeScript typings.

**Comment by sahilshahpatel** [comment]
Worked a little bit on this (still local to avoid interference -- just playing with D3 in React). The article above suggests making a `src/hooks/useD3.ts` file with a specific `useD3` hook function. I found it much simpler and easier to just call `useRef` and `useEffect` once each within my D3-based component.

In either case, setting this up was much easier than I expected. Will attempt more fancy map stuff with D3 next.

**Comment by Bone008** [comment]
Good enough integration for now.
