### ISSUE TITLE
Create mappings from "owners" to human-readable country/org names

### ISSUE THREAD

**Issue by Bone008** [Bone008/orbiteye#30]
They should be shown in the "Owner" dropdown instead of the short codes.

See SATCAT for the mapping: https://celestrak.com/satcat/sources.php

See [the spreadsheet](https://docs.google.com/spreadsheets/d/1bWLvvn11pkFoWONQY0W00fq5BEsncXgFrQVKWN93NWM/edit#gid=0) for more info.

**Comment by Bone008** [comment]
There is lots of complexity about how to handle "combo" owners such as "US/China" but for now let's just ignore them and put the full string as in the source data.

**Comment by sahilshahpatel** [comment]
One improvement we could still do on this is to re-sort by the readable names so that it's still in alphabetical order from the user perspective.
