### ISSUE TITLE
Researching of the orbit type

### ISSUE THREAD

**Issue by jackiefasty** [Bone008/orbiteye#34]

**Comment by jackiefasty** [comment]
How satellites save the information about to which orbit they belong to, and how can be visualized on the 2D map

**Comment by sahilshahpatel** [comment]
May be useful: https://www.atmosp.physics.utoronto.ca/people/strong/phy499/section2_05.pdf
See section 2.3 -- it has detailed descriptions of each orbit, but the first paragraph of each is a relatively down-to-earth explanation!

**Comment by Bone008** [comment]
2 sets of descriptions needed:

- [x] What is LEO, MEO, Geostationary, Elliptical?
- [x] What are the 4 view modes (Orbits, Origin, Launch, Decay) and what is shown there?

**Comment by OctaveLT** [comment]
I put in the Brainstorming doc

**Comment by OctaveLT** [comment]
Here it is: 

https://docs.google.com/document/d/1-WQRPnEhn_oBTqc5AZ3TsCpyYSNXSGMuY4YW4QkhMHs/edit
