### ISSUE TITLE
Switch to better map projection for 2D views

### ISSUE THREAD

**Issue by Bone008** [Bone008/orbiteye#55]
Mercator bad  🧂 

We can use [d3-geo-projection](https://github.com/d3/d3-geo-projection) in order not to suffer from Robinson maths pain.

**Comment by sahilshahpatel** [comment]
Just as a note: I couldn't find a way to re-map the static topographic map of the earth (it's natively Equirectangular) with D3. There is a [NASA tool](https://www.giss.nasa.gov/tools/gprojector/) which is supposed to be able to do it, but I couldn't get it to work.

So if we want the chloropleth map and the orbit trace map to use the same projection it will have to be equirectangular. If we don't care about that, then yes d3 has a Robinson-like projection called "Natural" or something like that.
