### ISSUE TITLE
Create 'About' page and do its access as link tag

### ISSUE THREAD

**Issue by jackiefasty** [Bone008/orbiteye#76]

**Comment by jackiefasty** [comment]
The page has to contain:
- link or HTML tag to demo video 2 minutes long
- information about group members, including workload distribution
- short project description
- learning objectives reached 
- citations, references, source of code and data to pass
- month and year of created visualization. Include last updated date
- Creative Commons License (Attribution-NonCommercial)

**Comment by sahilshahpatel** [comment]
Page layout is complete. Page linking is _almost_ complete. What's left I think is to add a header or something to the landing page which contains both the name OrbitEye and a link to the about section. I will work on that next!

**Comment by sahilshahpatel** [comment]
Navbar/header added in 8094b45dfbd166ef7edbf7b965035c4daa583f96. The way everything hooks up here is definitely not the cleanest, but it's also not the worst... I'm open to suggestions though 😄

Closing for now since I don't see us spending much more time on this before the deadline.
