### ISSUE TITLE
Record Demo-video and add the link

### ISSUE THREAD

**Issue by avelinpv** [Bone008/orbiteye#79]
Record the Demo and put it as a YouTube video on the About page. 

Order of what should be shown in the Demo:
1. Briefly overview the mode-menu. 
   - Briefly explain that there are 3 modes. 
2. Enter Orbit mode
   - Zoom the globe in and out, rotate the globe
   - Breifly explain warning sign
   - Show and explain the active check-box
   - Filter: Select and explain GEO orbit types.
     - Explain that diffrent colors on the orbits are types 
     - Show educational slides briefly
     - Show off-axis GEO sattelites
   - Briefly go through and explain the rest of the filters.
3. Enter Groud track mode
   - Explain what they see and how they are the orbits they just saw in 3D
     - Show an example of one cool orbit types ground track. 
   - Select an orbit and show detail panel
   - Use timeline. Its based on launche dates. 
4. Enter Orgin mode
   - Tell that the filters are reset
   - Explain what the color represent
   - Show the collaborations and explain what they are
   - Use timeline and show how to explore time in origin mode
5. Ending

**Comment by sahilshahpatel** [comment]
Some extra thoughts:
- For ground track mode, using the example I did with GEO satellites in orbit mode, seeing the one that's off axis, and then comparing them in ground track mode could be nice
- For origin mode, watching Russia fade out as you eliminate older satellites on the timeline seems like an interesting demo

That's just maybe some specific ideas, but your outline is great!

**Comment by avelinpv** [comment]
Super good suggestion with the GEO, I really liked that part in the final presentation demo you did so will try to do something similar.

Great idea, that one with Russia is similar to what I had in mind too. Will defenetly try it out in the demo video.
